### ISSUE TITLE
BetterFPS Taylor Algorithm Causes Severe Biped and Graphic Glitches & Oddities

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/New-MMD-Public-Pack#13]
This a known issue and if your experiencing it, the above mentioned Algorithm is most likely the cause.

I originally reported this issue back in 1.10.2 here https://github.com/Guichaguri/BetterFps/issues/62

**Comment by TheSpicePhantom** [comment]
Thanks for letting us know, but why report it here and point to another issue. If the algorithm is weird for you, don't use it.

Like the dev said, for some it works and for some not.

**Comment by Morpheus1101** [comment]
I reported it here in case others run into the same issue on the pub server an goto report an issue here
