### ISSUE TITLE
Possible removal of Morphs Tweaks.

### ISSUE THREAD

**Issue by carstorm** [MinecraftModDevelopment/New-MMD-Public-Pack#14]
The features of this mod is included in Quark making this one redundant.

**Comment by TheSpicePhantom** [comment]
FastLadder mod will be removed. Thanks for your info!

**Comment by ProxyNeko** [comment]
MorphsTweeks was added for one feature that is already added by another mod. It is to be removed in the next update.

**Comment by ProxyNeko** [comment]
To be dealt with at the same time as #16 preferably

**Comment by Morpheus1101** [comment]
What mod does the same thing as Morphtweaks?  ive yet to see any mod that adds the ability to add what ever enchant you like via a recipe and of all levels?

**Comment by ProxyNeko** [comment]
Fast Ladders removed in version 0.0.7

**Comment by ProxyNeko** [comment]
Quote from in-game public server chat
"RelayBOT - Today at 15:53
[TheSpicePhantom] my reply: No pot luck... just vanilla mechanics
[TheSpicePhantom] its true, it can only enchant level 1, but you are able to combine the books to get level 2,3,4 and 5"

MorphsTweaks removed.
