### ISSUE TITLE
[Mod Request] Paint All the Things

### ISSUE THREAD

**Issue by carstorm** [MinecraftModDevelopment/New-MMD-Public-Pack#15]
As discussed during internal discussions, add https://minecraft.curseforge.com/projects/paint-all-the-things

**Comment by ProxyNeko** [comment]
This will need a config generating and tweaked ready for the pack.

**Comment by ProxyNeko** [comment]
Can't add this mod just yet as the dev is calling a client-side class on the server.

https://hastebin.com/uzivojapoz.py

**Comment by carstorm** [comment]
This has been fixed already but not released yet: [](https://github.com/Eladkay/PaintATT/issues/7)
