### ISSUE TITLE
A vote to keep or remove the following mods.

### ISSUE THREAD

**Issue by ProxyNeko** [MinecraftModDevelopment/New-MMD-Public-Pack#16]
Please vote "keep" or "remove" with your reasons as to why if any below. 

Terraqueous: Mostly stuff added by other mods and I've not seen a great deal of usage of the mod as a whole and I feel it adds close to nothing to the progression of the pack bar time wasted eating it's food all day because of it's low hunger value.

Snad: Because who needs this when we have other mods that grow stuff just as fast without this. (Duplicate because of farming content in the pack.)

**Comment by carstorm** [comment]
Terraqueous: Remove for the same reasons you listed.

Snad: Keep because it only adds one thing and while the same can be achieved with other things in the pack none are as early game as this is.

**Comment by Morpheus1101** [comment]
I vote to remove both.

Terra .. well its basically a useless mod with as said nothing of value added and although ive looked into the mod, i cant say it adds anything of value.

Snad .. i didnt even know it was in the pack, heard of it or ever have or would use it tbh

**Comment by saramaebee** [comment]
Terra: agh i'm torn. I'm a big fan of the different fruit trees. If there's another mod that adds fruit trees, then I'm down to remove it.

Snad: id never heard of it, but now that I see it, it's rather quite useful. it's cheap enough that I like it. I vote keep

**Comment by Virtuoel** [comment]
Terra: Seconded on the Life Fruit. Also Burnium is a nice fuel and the Cloud Furnace and Storm Forge can be quite useful. My main concern is that removing it could leave gaping holes in the Nether and End where the ores used to be. I would say remove if it wasn't for those points. 

Snad: Also completely didn't see it in the pack. Keep, remove, I don't mind either way. Seems to be quite lightweight.

**Comment by ProxyNeko** [comment]
The life fruit can be replaced with some hearts from one of my mods that I plan to request be put in in the future along with the trees as I was planning on making some of my own fruit trees at some point so that should cover those points for two of you.

The nether and end will be reset soon:tm: but I don't have a date for when yet. (I WILL let you all know before I reset those though so you have time to recover blocks and items from them.)

**Comment by Ruchian** [comment]
Terraqueous - It does have some interesting things, but I never worked with it well enough. I know about the storm forge that auto charges and auto repairs stuff over time without it costing anything. It is an interesting-looking (indestructable) multiblock structure. The cloud houses are interesting in a way, but the downside is their incompatibility with other blocks. Burnium provides nice fuel. Life Fruits, might be interesting. (I'm not too much in combat and only think your last HP point matters, not the rest, so..) (I am undecisive with this one)

snad - It's probably not going to be used (at all). If it is, maybe for a farm, for a small speed upgrade on top of the accelerator blocks, if one thinks about it. I mean there is an off chance you'll even notice the mod installed. There are too many other things around, making things on sand grow fast enough on their own even without speed upgrades. I think you can remove it, no one would notice. xd

**Comment by KamiSami** [comment]
Terraqueous: Pretty much what Ruchia said, though i would like to have it in the pack!

Snad: Idk what this even is so i don't care ^^;

**Comment by RedstoneParadox** [comment]
I honestly don't like Terraqueous' aesthetic when juxtaposed with Minecraft's aesthetic, so I vote for it to go.

Snad is unbalanced and only works on sugar cane, so I vote for that to go as well.

That is, assuming I'm not too late to vote.

**Comment by ProxyNeko** [comment]
It is still open to voting but things are looking like they will both stay in so far. I will see what happens by the time I close the ticket.

**Comment by carstorm** [comment]
Current Vote totals as of now: 
Terraqueous: Remove 4, keep 1, Remove if... 2, Indecisive/don't care 1, Total 8
Snad:             Remove 4, keep 1, Remove if... 0, Indecisive/don't care 3, Total 8

**Comment by ProxyNeko** [comment]
Final result conclusion.
Both mods have enough requests to be removed but I will only remove SNAD for update 0.0.8 and when I get time I will work on my mod to add in a Life Fruit like item for those who wish to keep that kind of item along with the fruit trees I planned on doing.

Terraqueous: Staying for now.
SNAD: Removed in 0.0.8.
