### ISSUE TITLE
{1.12.2] Mod Request: Avaritia

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/New-MMD-Public-Pack#17]
https://minecraft.curseforge.com/projects/avaritia-1-10/files

The reason im asking for this mod other then because its mine, is that it adds quite a lot of very very late game items that take a lot of effort to make and obtain even for very Late game and with so many of us including myself at the stage of building an making everything an anything with stockpiles of resources, it would add a very much needed imho challenge and goal for folks to work towards once at end game an looking for things to do and to keep players interested.

**Comment by ProxyNeko** [comment]
Car and I approve but I am waiting on @TheSpicePhantom's thoughts so this will likely wait until version 0.0.8

**Comment by Ruchian** [comment]
You might need to add your own large crafting recipes though. I am not sure if they come with those things on their own.
I recall that there was another mod in the pack present which provided a large crafting grid, but remained unused. (I'm not certain if this was removed now though)
Maybe you simply are too good in the game and way too fast. xD

**Comment by Morpheus1101** [comment]
Atm it has recipes that use the 9x9 and i am in the midst of adding more 9x9 recipes for creative items which will be in the next version in a few weeks of Avaritia

**Comment by ProxyNeko** [comment]
Avaritia has been approved. Will be pushed within version 0.0.7
