### ISSUE TITLE
Uranium & Uranium 238 Issue

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/New-MMD-Public-Pack#18]
The issue of turning Uranium ingots to blocks and blocks to ingots is something that still remains.

Grid of 9 U238 = 1 Block of Uranium, so it maybe a case of IC2 and MMe not working well together

**Comment by TheSpicePhantom** [comment]
will have a look, cant promise changes this week, bout no time to do things in my own life

**Comment by ProxyNeko** [comment]
Seems it is fixed in version 0.0.7 (so far) if it happens again post back and I will look into it.

**Comment by Morpheus1101** [comment]
This issue still occurs in v7

**Comment by ProxyNeko** [comment]
Manually created recipe for next update see pins should you want to download and add it in for singleplayer but it will be on the server after the restart.
