### ISSUE TITLE
v6c Items bought form Shops Do not appear in inventory

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/New-MMD-Public-Pack#19]
Carrots had bought 2.5k worth of Nether Stars form me and dindt show up in inventory, after manually giving the stars, i purchased some stars myself from SpicePhantoms shop and the same thing occured, re-tested with Proxys shop of carrots and again same issue occured.  The transfer of money occurs but the items do not show up.

**Comment by ProxyNeko** [comment]
This seems to be a bug as it works in creative mode to buy and sell from shops so I will try an update then if that does not fix it I will push it to the developer.

**Comment by ProxyNeko** [comment]
This bug seems to persist even in version 0.0.7 so I will post back to the author and see what we can find from there.

**Comment by ProxyNeko** [comment]
Fixed and release planned for Tuesday. The fix will be added to the pack as soon as it is out ready for update 0.0.8.
