### ISSUE TITLE
Botania severe bugs

### ISSUE THREAD

**Issue by KamiSami** [MinecraftModDevelopment/New-MMD-Public-Pack#21]
Using so far i think any kind of magic rod causes you to DC with message saying internal server error and equipping aura ring or flugel tiara with flugel wings does same thing

**Comment by Morpheus1101** [comment]
While testing only in SinglePlayer, i managed to equip a Tiara and 2 Aura rings and using different rods to no ill affects or crashes/timeouts .. perhaps this only affects SMP

**Comment by ProxyNeko** [comment]
Fixed. Thankfully.
