### ISSUE TITLE
Must have mod!! (Request)

### ISSUE THREAD

**Issue by KamiSami** [MinecraftModDevelopment/New-MMD-Public-Pack#22]
https://minecraft.curseforge.com/projects/wizardry-mod

Yes 'w'?

**Comment by carstorm** [comment]
My first thought on this mod, specially based off the very beginning of the description, "THIS MOD IS IN EARLY ALPHA. IT CURRENTLY LACKS A LOT OF CONTENT AND YOU WILL FIND BUGS." is to wait for a more feature complete and stable version before even considering to add it.

**Comment by TheSpicePhantom** [comment]
as mentioned above

**Comment by ProxyNeko** [comment]
Request closed for now but please do try again when the mod has become more stable :)
