### ISSUE TITLE
Mod Request: Wireless Crafting Terminal

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/New-MMD-Public-Pack#23]
Link: https://minecraft.curseforge.com/projects/wireless-crafting-terminal/files

Reason: With the extensive size my base is, its quite annoying and frustrating to have to keep going back to the main console of my AE system everytime i need extra things that need to be crafted and have wanted to use this.  So hence im asking as this would be a godsend for a lot of folks i imagine.

**Comment by ProxyNeko** [comment]
I lean towards the approval of this mod more than anything but we will see what the others say.

**Comment by carstorm** [comment]
I approve.

**Comment by saramaebee** [comment]
I second this

**Comment by ProxyNeko** [comment]
Added in 0.0.8
