### ISSUE TITLE
Mod Request: OpenComputers

### ISSUE THREAD

**Issue by saramaebee** [MinecraftModDevelopment/New-MMD-Public-Pack#25]
Please please please. I can do even more fancy stuff with OC than with CC, and I'd like to get into it

**Comment by ProxyNeko** [comment]
I approve as OpenComputers is more of a late game version and has much more compared to CC.

**Comment by carstorm** [comment]
Approve since some prefer it over CC and it can do some things CC can't. I will personally keep using CC.

**Comment by saramaebee** [comment]
I think a mixture of both is best

**Comment by ProxyNeko** [comment]
Added in 0.0.8
