### ISSUE TITLE
Tiny Progressions Bag -> throwing items out causes a crash

### ISSUE THREAD

**Issue by Ruchian** [MinecraftModDevelopment/New-MMD-Public-Pack#27]
(as the title says)

When you click on an item to pick it up, drag it out of your inventory and release it with a second click, normally the item is dropped, which is something similar to what happens when you press Q to an item you have selected in the hotbar.

You can do this while you have a chest open or some other form of an inventory as well.

When you have the Big Bag (from tiny progressions) open up displayed however and for some reason are trying to throw an item out, you can an index out of bounds exception -999.

Frankly it's annoying. I advise people to use a different bag.

**Comment by ProxyNeko** [comment]
https://github.com/Kashdeya/Tiny-Progressions/issues/88 Noted and will update when we can

**Comment by ProxyNeko** [comment]
Mod has not updated since so will have to wait until 0.0.9
