### ISSUE TITLE
Pack dev notes.

### ISSUE THREAD

**Issue by ProxyNeko** [MinecraftModDevelopment/New-MMD-Public-Pack#28]
See how The Secret Rooms mod is doing with HWYLA integration.

**Comment by carstorm** [comment]
Can you elaborate on what the issue is please?

**Comment by ProxyNeko** [comment]
Reminders and notes for myself and others should we need them. Kinds says it in the title lol

**Comment by carstorm** [comment]
Lol I missed the title completely and even now, took me a min to "find" it.

**Comment by ProxyNeko** [comment]
Secret rooms and HWYLA integration finished just awaiting release in the next day or so.
