### ISSUE TITLE
Mod Request: RandomPatches

### ISSUE THREAD

**Issue by RedstoneParadox** [MinecraftModDevelopment/New-MMD-Public-Pack#29]
Increases the hardcoded read and login timeouts, which would (hopefully) fix the issue I've been having of not being able to log in.

**Comment by ProxyNeko** [comment]
We already doubled it from the previous ticket you made about the issue I don't know if there is much more we can do unless @TheSpicePhantom says anything new.

**Comment by TheSpicePhantom** [comment]
Nope, since we already have it, it's server side only

**Comment by ProxyNeko** [comment]
Closed as it already exists.
