### ISSUE TITLE
EnderPay mod recipe tweak needed.

### ISSUE THREAD

**Issue by ProxyNeko** [MinecraftModDevelopment/New-MMD-Public-Pack#3]
Crafting recipe needs a small tweak to get more output from the recipe due to not getting a blank banknote back once it has been used.

Once crafted you can right click to enter an amount as a note (e.g. 10) and it will be taken from your account in game.

But if you put the wrong number or you want to change it you can't.
You just need to use it elsewhere or right click to put the funds back into your account

![2017-12-30_03 37 05](https://user-images.githubusercontent.com/19393068/34451084-2f255e86-ed13-11e7-885e-c710092983c3.png)

Might also be a good idea to see if the creator wanted to not give the player a blank banknote back when the credits are used up on right click or if this is a missed feature/bug.

Current issues open with this mod as of writing:
https://github.com/kamildanak/EnderPay/issues/11

**Comment by kamildanak** [comment]
Hi, I just changed the filled banknote behavior - when used it should return blank banknote to player.
https://github.com/kamildanak/EnderPay/commit/c78182a0c0791da07c2597f45cb3fdf522d77b64 (enderpay-1.12.2-1.0.1.0.jar)
https://github.com/kamildanak/VendingBlock/commit/734a701874f1787e70e86abcea1a18a40ddf852f (vending-1.12.2-3.0.1.0-rc1.jar)

**Comment by ProxyNeko** [comment]
Nice I look forward to these changes :D
