### ISSUE TITLE
Mod request: cyberware

### ISSUE THREAD

**Issue by Skarmarm** [MinecraftModDevelopment/New-MMD-Public-Pack#30]
Link: https://minecraft.curseforge.com/projects/roboticparts
Also, sorry if this isn't as flushed out as it should be.

**Comment by ProxyNeko** [comment]
I approve.

**Comment by carstorm** [comment]
I'm personally not too into it but know it is popular and some players like it...therefore approve.

**Comment by carstorm** [comment]
Implemented in 0.0.8
