### ISSUE TITLE
Mod Request: CompactStorage

### ISSUE THREAD

**Issue by carstorm** [MinecraftModDevelopment/New-MMD-Public-Pack#31]
Request for https://minecraft.curseforge.com/projects/compactstorage|

Though some content is duplicated from other mods already present in pack, this mod [IMO] does things better and is meant for more mid-late game as it requires lots of iron (or string). I personally prefer this over Iron Chests (and there is no equivalent bag of this level). It only adds 4 ids (6 as of latest update).

Edit: could take off one or two IDs by disabling the duplicate content (barrels and drums)

**Comment by ProxyNeko** [comment]
Is this a request to swap the two mods (one for the other) or have both in the pack? It would take time to remove the older mod as people may be using it and it would need a few announcements to help migrate them to the new chests.

**Comment by Virtuoel** [comment]
As car said, seems like a good mid-late game storage mod. Could work nice as a later game upgrade after AA crates and Cyclic bags. The customizability is also quite nice, with bag colors sounding useful for player inventory management. 

I agree about disabling its barrels and drums, which due to their lack of customizability sound somewhat bland and duplicated better by existing mods.

**Comment by carstorm** [comment]
Request to add this one not to replace any mods. Iron chests is still better for early game and some people may still prefer that late game. IMO the useful duplicate content (chest and bags) should be allowed with the unuseful duplicate content being disabled (drums and barrels)

**Comment by ProxyNeko** [comment]
That's fine then I approve it.

**Comment by carstorm** [comment]
Implemented in 0.0.8

**Comment by carstorm** [comment]
For some reason this wasn't added like it was suppose to be. Will be added in next update instead.

**Comment by ProxyNeko** [comment]
@carstorm is it in the pack now?

**Comment by Morpheus1101** [comment]
Yes it is
