### ISSUE TITLE
[Config Change] Increase distance OpenBlocks Elevators

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/New-MMD-Public-Pack#32]
Id like to request these changes be added to the config please:

# The maximum amount of blocks the elevator can pass through before the teleport fails
    I:maxPassThrough=64

# The range of the drop block
    I:searchDistance=64

**Comment by carstorm** [comment]
The default for "I:maxPassThrough" is 5. I agree this is low but believe 64 is too high. IMO 10 seems more reasonable. 

The default for "I:searchDistance" is 20 which I agree is too low. I agree that 64 seems more reasonable.

**Comment by ProxyNeko** [comment]
I agree with the changes that carstorm has suggested over the more overpowered ones initially posted. Hopefully, this will be enough for you.

**Comment by ProxyNeko** [comment]
Changed in 0.0.8
