### ISSUE TITLE
Mod Request: Matter Overdrive

### ISSUE THREAD

**Issue by Virtuoel** [MinecraftModDevelopment/New-MMD-Public-Pack#34]
https://minecraft.curseforge.com/projects/matter-overdrive

Provides some technological alternatives, but not full replacements, to some mods that are more magical: 

Resource creation provided by mods like Mystical Agriculture can be done using the machines that make up the Matter Replication system. Matter values can be easily tweaked in the configs or with commands for rebalancing purposes. Energy costs could (maybe should be to make it more endgame?) be changed as well.

The Android system provides an interesting choice to players of whether they want to use the Everlasting Abilities Totems, or if they want to become an Android that provides its own benefits and abilities, but be unable to use potion effects like those from the Totems. 

Has fancy customizable ranged weapons. 
Adds fancy space decoration blocks. e.g.: Holographic Sign. 
Looks quite nice in general. 

Maybe disable the Google Analytics gathering in the config if added?

**Comment by carstorm** [comment]
Seems like it would need a lot of config tweaking if added. Seems like a lot of it would be cool and used. I approve.

**Comment by ProxyNeko** [comment]
Mod is under review/internal testing. Should have a decision fairly soon:tm: sorry for the delay.

**Comment by Morpheus1101** [comment]
Having gotten to play with this mod a little bit and looking through a lot of comments, issues and stability, im afraid at this stage of its Development, it's a very risky mod to use in the pack and has the ability to cause quite significant issues as well as complete world corruption.  When the mod is out of Beta and a lot more stable, i myself would very much like to play around with it in a Multiplayer environment.

**Comment by Virtuoel** [comment]
Fair enough. I suppose I'll poke this issue again once the mod reaches a more stable stage of development.
