### ISSUE TITLE
[Mod Request] AI Improvements

### ISSUE THREAD

**Issue by carstorm** [MinecraftModDevelopment/New-MMD-Public-Pack#36]
This mod is meant to improve performance (on both sides) by improving mob AI.
Do you think it would be worthwhile to add?
https://minecraft.curseforge.com/projects/ai-improvements

**Comment by Morpheus1101** [comment]
When i was having issues on my modded server i added this mod in due to recommendations of it doing the same thing, however, i noticed no difference at all, perhaps it'll be different for MMD-Pub..
