### ISSUE TITLE
Mod Bugs/Feature Requests to Chase Up

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/New-MMD-Public-Pack#37]
- [ ] https://github.com/MineMaarten/IGW-mod/issues/93
- [x] https://github.com/PrinceOfAmber/Cyclic/issues/735 (Items spitting out of harvester when full)
- [x] https://github.com/progwml6/ironchest/issues/130
- [x] https://github.com/ValkyrieofNight/EnvironmentalTech/issues/103 - Draconium Ore IssueUnobtainable

**Comment by ProxyNeko** [comment]
Pack discontinued, closing.
