### ISSUE TITLE
[Mod Request] Voidcraft

### ISSUE THREAD

**Issue by Ruchian** [MinecraftModDevelopment/New-MMD-Public-Pack#39]
Voidcraft is a mod that adds a frame of mystery with a dimension to explore to the game.
It's relatively new and still in development (as it is incomplete, similar to abyssalcraft). I think its very mmd. xd

Currently the only dimensions in the server are:
Spectre (Random things: meant for personal use)
Deep Dark (XU2: A bit mysterious, not meant for exploring though. People use it to mine.)
ExtraUtils2_Quarry_Dim (XU2: cannot explore)
MINING_WORLD (meant for mining, as the name says)
the_nether (minecraft, which we're used to even with the added biomes (ocean is still a mystery))
overworld (...)
Storage Cell (Applied Energistics: Meant for storage, not for living. xd)
JED Surface  (no clue... we can't go there anyway)
The Abyssal Wasteland ... which will be removed (abyssalcraft)
The Dreadlands, which will also be removed (abyssalcraft)
Omothol, will be removed (abyssalcraft)
The Dark Realm, will also be removed (abyssalcraft)
CompactMachines, (CompactMachine: meant for storage)
tartarus, no clue... is this GM island? 

Anyway, with the removal of abyssalcraft there isn't any very special place to explore left in the game. Even if progression through it is easy and even if there isn't much else to do after wards, it still added a bit of.. something other than the overworld to visit. (a completely different looking, mysterious place.)

This is why I made this request.
https://minecraft.curseforge.com/projects/voidcraft

It turns the void into a dimension with some weird dark mysteries. (so, when you fall down in the end for example, you'll end up there, you'll still die due to fall damage though.)

Since it is kinda mysterious and magical, I'm pretty sure people might be interested.
But considering the reduction of CPU and RAM load is the priority here, you can ignore it if you wish. xd

**Comment by Morpheus1101** [comment]
I certainly wouldn't be against having this, however this existing issue concerns me ... https://github.com/Tamaized/Dal-Quor/issues/222

**Comment by carstorm** [comment]
It seems interesting but as morph said there are some major issues that make me concerned. After those issues are fixed I would give it my approval. 


Also just so you know, the "JED Surface" dim is the dim that you first spawn into.
