### ISSUE TITLE
WAILA crashing on tree grow with bonemeal.

### ISSUE THREAD

**Issue by ProxyNeko** [MinecraftModDevelopment/New-MMD-Public-Pack#4]
Got a crash from WAILA when I bonemeal a sapling from Terraqueous and it turns into a tree and this has happened three times so far with the same two mods with both of my crashlogs being the same.
This does not happen with other trees.
[Crashlog gist](https://gist.github.com/ProxyNeko/7be1fe0f16835f1d4edc42af38dedf34)

Terraqueous version: 1.12.0-1.4.6
WAILA version: 1.8.23
Forge version:14.23.1.2560
Modpack version: RC4-0.0.4

**Comment by TehNut** [comment]
@ShetiPhian You're passing a null stack in your `IWailaDataProvider#getWailaStack()` agian.

![](https://cdn.discordapp.com/attachments/302144329785278464/397126877967286272/unknown.png)

**Comment by ShetiPhian** [comment]
It been a long time since one of these overlooked null stack was found, with luck this is the last one.

I'll push a fixed build after work.

**Comment by ProxyNeko** [comment]
Would you let us know when you do please would like to see this update asap

**Comment by ShetiPhian** [comment]
Managed to get it fixed, compiled, and uploaded before heading out.
Curse just needs to process it now.
https://minecraft.curseforge.com/projects/terraqueous/files/2516412

**Comment by ProxyNeko** [comment]
Will be home in a bit to test it out thanks for the quick fix

**Comment by ProxyNeko** [comment]
Issue resolved :D all good @carstorm
