### ISSUE TITLE
[Mod Request] NuclearCraft

### ISSUE THREAD

**Issue by Intipablo** [MinecraftModDevelopment/New-MMD-Public-Pack#40]
Nuclearcraft looks like a great mod that I really want to dive into and learn.

For those of you that don't know it's a modern physics mod (Has all the machines that you see and all that, supports multiple power API's) focused on fusion and fission reactors. Similar to Extreme Reactors except more in depth.

https://minecraft.curseforge.com/projects/nuclearcraft-mod

The mod is being constantly updated however with bugs being fixed etc. So waiting might be a good idea.

**Comment by Morpheus1101** [comment]
I would be up myself for having it, i know its updated quite regularly for bugs.

**Comment by carstorm** [comment]
Not sure if I would personally use it but it seems like a cool mod. I approve.

**Comment by ProxyNeko** [comment]
Added in in 0.0.10
