### ISSUE TITLE
[Mod Request] Minewatch

### ISSUE THREAD

**Issue by KamiSami** [MinecraftModDevelopment/New-MMD-Public-Pack#41]
Fun mod that works nicely on early/mid game, it's mod that gives weapons and abilities like in game called Overwatch.. Still in work in progress but what i have tested, it has worked pretty well.

https://minecraft.curseforge.com/projects/minewatch

Edit: Also i should note that if it will be added, i recommend changing damage scale in config to 2.0 as 1.0 was intended for vanilla Minecraft with that mod only.. Perhaps some other configs :)

**Comment by carstorm** [comment]
This mod seems like it would fit in much better in a tailored (i.e RPG like) pack rather than a  kitchen sink pack.

**Comment by KamiSami** [comment]
I guess so then, well i do appriciate for response at least, feel free to close this if it is deemed unfit for pack

**Comment by Morpheus1101** [comment]
I have to agree that its suited more to an RPG PVP style map
