### ISSUE TITLE
[Mod Request] Elemental Creepers Redux

### ISSUE THREAD

**Issue by T145** [MinecraftModDevelopment/New-MMD-Public-Pack#42]
It's good and stable! All spawn rates and explosion characteristics are configurable, for those mod pack geeks out there!

[https://minecraft.curseforge.com/projects/elemental-creepers-redux](https://minecraft.curseforge.com/projects/elemental-creepers-redux)

**Comment by Morpheus1101** [comment]
I Approve

**Comment by ProxyNeko** [comment]
I approve also.

**Comment by Morpheus1101** [comment]
ElementalCreepers-v4.1.4.g9a92a3b currently crashes server side

**Comment by T145** [comment]
https://minecraft.curseforge.com/projects/elemental-creepers-redux/files/2543353

**Comment by ProxyNeko** [comment]
Added in in 0.0.10
