### ISSUE TITLE
[Mod Request] EnderZoo

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/New-MMD-Public-Pack#43]
This would add a few more different Mob's and useful things to help make things even more interesting.

https://minecraft.curseforge.com/projects/ender-zoo/files

**Comment by ProxyNeko** [comment]
How stable is it because I know the ender mods are fairly new to 1.12.2 currently all I know is this one has been out for a few months now maybe

**Comment by Morpheus1101** [comment]
I have this in a few packs, 1 of which is released which ive spent considerable time playing an only had 1 issue which was caused by another mod, staff server also uses it

**Comment by carstorm** [comment]
Approve

**Comment by ProxyNeko** [comment]
If it works I approve but maybe see if you can turn down how deadly the tiny endermen are due to them being tricky to kill even on normal and killing people multiple times in the same area.

**Comment by carstorm** [comment]
It will def need some tweaking if added. I noticed one of the features it adds is granular control over all mobs (including vanilla and those added by other mods.

**Comment by ProxyNeko** [comment]
Added in in 0.0.10
