### ISSUE TITLE
[Mod Request] Vic's Modern Warfare

### ISSUE THREAD

**Issue by sell488** [MinecraftModDevelopment/New-MMD-Public-Pack#45]
An incredibly cool gun mod that adds many types of guns as well as a cool, unique kinds of grenades and attachments. The only downside is that mags don't stack :(

**Comment by carstorm** [comment]
Even though this is a kitchen sink pack, its not meant to be gun focused or have any serious PvP so my vote is to decline this request due to this mod being suited for a more focused and/or PvP focused pack.

**Comment by Morpheus1101** [comment]
Gun's are more suited to a PVP style map then what we currently have running, so im afraid im also voting to decline.

**Comment by ProxyNeko** [comment]
As this is not a pvp pack currently we will deny this mod request.
