### ISSUE TITLE
Set Up Shop Dim to auto gen server side.

### ISSUE THREAD

**Issue by carstorm** [MinecraftModDevelopment/New-MMD-Public-Pack#46]
This is mainly a self note that this must be done. This is the main thing I want to do before I personally say the pack is ready for official release and will be my main focus the next few days.

**Comment by Ruchian** [comment]
What is the shop dimension supposed to look like?
A large square platform surrounded by ocean till bedrock and beyond that void? (kinda like an island?)

Maybe you can make a giant mall. xD .... and the let stands within this mall be the location for shops and item sales.

**Comment by carstorm** [comment]
I'm currently trying to use Recurrent Complex to make a grid pattern of plots but am having issues of it not tiling properly as can be seen in the image below.

![image](https://user-images.githubusercontent.com/7497589/37877123-dfc74ad8-301b-11e8-81e1-f2a186228a5b.png)

**Comment by enderger** [comment]
Or build a square and clone it.

**Comment by carstorm** [comment]
This now works client side. Still trying to figure out how to get it to work server side. For now I manually copied the files from the client to the official server.

**Comment by Morpheus1101** [comment]
is this still a thing needing to be done for ServerSide ?

**Comment by carstorm** [comment]
I did it for our server manually, however it still doesn't work on dedicated servers yet.
