### ISSUE TITLE
Disable Kendrel Knights

### ISSUE THREAD

**Issue by T145** [MinecraftModDevelopment/New-MMD-Public-Pack#47]
And the world was one small thing better.

**Comment by carstorm** [comment]
What mod is this from? I know in game you said they spawn when you use the wrong tool on dirt.

**Comment by T145** [comment]
EnderZoo

**Comment by ProxyNeko** [comment]
This mob only spawns when you don't use a shovel on grass and dirt and should only do one or half a heart of damage before leaving you alone.

Knowing this I am quite happy to leave it be since it is easier than normal in this pack to make a shovel but the final call comes down to @Morpheus1101.

**Comment by Morpheus1101** [comment]
Being they have only half heart of health and only spawn when mining dirt without a tool, im inclined to leave it in, as getting a tool an using it even form start of game is rather simple.
