### ISSUE TITLE
[Mod Request] Redstone Flux Arsenal

### ISSUE THREAD

**Issue by knoxhack** [MinecraftModDevelopment/New-MMD-Public-Pack#48]
Description:
Features in incoming updates:
Base Metals RF Crack Hammer
Tinkers RF Modifier
RF Energized Hammer (Breaks 3x3)
RF Energized Drill (Acts like a 3 in 1)

Link:
https://minecraft.curseforge.com/projects/redstone-flux-arsenal

**Comment by carstorm** [comment]
I'm indifferent if this gets added or not. I feel like it would get very little use due to being under powered compared to other stuff in the pack that can be gotten just as easily.

**Comment by Morpheus1101** [comment]
With the newer additions this could be quite handy, but as car said, with what is currently available in the pack, id be concerned about it not being widely used if at all.
