### ISSUE TITLE
[Mod Request] Dense Metals

### ISSUE THREAD

**Issue by knoxhack** [MinecraftModDevelopment/New-MMD-Public-Pack#49]
Description:
Dense versions of all Vanilla ores.
Dense versions of all Base Metals Ores.

Link:
https://minecraft.curseforge.com/projects/dense-metals

**Comment by carstorm** [comment]
I'm overall indifferent if this gets added or not. It has limited mod support as compared to [Dense Ores](https://minecraft.curseforge.com/projects/dense-ores) (not updated past 1.11 though) which is a  turn off but is the only mod of this genre that I know of that's updated to 1.12.

**Comment by Morpheus1101** [comment]
With a lot further support for a much wider range of mod ores i could se this being handy, but not as it currently stands.

**Comment by ProxyNeko** [comment]
I think if this hooked into MMDOreSpawn and used the ore's from that and other mods to come into alignment with the number of mods covered then I would approve but I would need to check if it does cover MMDOreSpawn first.

That being said I do want to reduce the world gen of normal ore's a lot more so it's not so full and adding this to the pack would be good to help clean up the amount of ore in the world gen as a whole by putting them into dense ore form.

**Comment by Morpheus1101** [comment]
At this stage we will hold off on this mod due to known issues with tps problems using in conjunction with OreSpawn
