### ISSUE TITLE
Extra bees

### ISSUE THREAD

**Issue by RockGoliath** [MinecraftModDevelopment/New-MMD-Public-Pack#5]
If the extra bees mod is stable, could it be added to the pack? I'm not completely sure what the protocol is for these things but I was told to post here.

**Comment by carstorm** [comment]
What mod are you referring to, this: https://minecraft.curseforge.com/projects/binnies-mods

**Comment by ProxyNeko** [comment]
![screenshot_20180122-155804](https://user-images.githubusercontent.com/19393068/35279308-a46e13ec-0044-11e8-931c-4e36e4d122d4.png)
Conformation of the desired mod.

**Comment by ProxyNeko** [comment]
![20180201_081633](https://user-images.githubusercontent.com/19393068/35668228-96950204-0728-11e8-8103-c08cd57b55ab.png)


I dropped mezz a message earlier that night to see how alpha the mod is and this was his reply so from me it's feeling like a no **for now** but I'm willing to keep my eyes on it to see if a beta or release comes about

**Comment by ProxyNeko** [comment]
Closed until the mod is more stable. Please make a new ticket when it has become a lot more stable :)
