### ISSUE TITLE
[Mod Request] Metal Crops

### ISSUE THREAD

**Issue by knoxhack** [MinecraftModDevelopment/New-MMD-Public-Pack#50]
Description:
A lightweight alternative to resource crops mods.
Fully integrated with Base Metals.

Link:
https://minecraft.curseforge.com/projects/metal-crops

**Comment by carstorm** [comment]
I vote no to this mod due to us already having a mod that has the same feature with much wider mod support.

**Comment by Morpheus1101** [comment]
Although future support for other wide range of things could be added, at this stage of the gamei feel it prudent to remain with what we have going.
