### ISSUE TITLE
[Mod Request] Utility Base Ores

### ISSUE THREAD

**Issue by knoxhack** [MinecraftModDevelopment/New-MMD-Public-Pack#51]
Description:
Utility mod that adds variety of non conventional ores, Please make sure to configure which ores do you want disabled/enabled from the configs before adding it (If gets added) to avoid unwanted ores.

Link:
https://minecraft.curseforge.com/projects/utility-base-ores

**Comment by carstorm** [comment]
I believe this was in the pack at one time but removed due to not really being used and just cluttering up worldgen...

With that being said I wouldn't mind adding it back in personally although what gets genned or how often should def get tweaked if it is added IMO.

**Comment by Morpheus1101** [comment]
Im of 2 minds about his really, would have to look at configuring it really well if it were added.

**Comment by ProxyNeko** [comment]
Although this was approved sadly it was missed out when the final update to release was made due to that we have chosen to mark it for the next pack we made instead. Apologies for this error.
