### ISSUE TITLE
[Mod Request] Better Agriculture

### ISSUE THREAD

**Issue by knoxhack** [MinecraftModDevelopment/New-MMD-Public-Pack#52]
Description:
Better Agriculture is a minecraft mod that currently adds 40 new breeds of farm animals (with more to come) plus lots of deco blocks and items that will enhance your farming experience, to help you build your dream farm.

Link:
https://minecraft.curseforge.com/projects/better-agriculture

**Comment by carstorm** [comment]
I approve

**Comment by Morpheus1101** [comment]
I like and approve of this as well :)

**Comment by ProxyNeko** [comment]
I lik dis >:3

**Comment by Ruchian** [comment]
I nicknamed it, the knox mmd many cows mod. xd
Anyway, cool. I didn't expect to find it on the mmd public server once again. ;p

**Comment by carstorm** [comment]
@Ruchian anyone is welcome to comment on mod requests. In the end the votes that matter is staffs but we will take community votes/ comments into consideration. This mod has already been approved though so expect to see it in the next update unless we discover a  major bug in it before then.

**Comment by Morpheus1101** [comment]
Has been added as of 0.0.11
