### ISSUE TITLE
[bug] Solar Flux Reborn recipes

### ISSUE THREAD

**Issue by Ruchian** [MinecraftModDevelopment/New-MMD-Public-Pack#56]
I noticed that the craft tweaker script says that solar flux reborn - solar panel tier 1's mirror ingredient, the mirror I's crafting recipe: [null null null], [glass_block, glass_block, glass_block], [null, iron, null] should give 3 mirrors Is, but instead gives 2 in game.
The second problem is the Tier 2 Solar panel. I noticed in game it is not craftable. The recipe has been changed to use a machine_frame, and yet, despite having the requirements, it doesn't allow it to be crafted.

I made a stack of tier 1 solar panels, not realizing this and now realized how much material I just wasted, which is unfortunate.

The original recipe had glass panes, not blocks, although the iron requirement is still normal and it gives 2 panels, not 3. xd

**Comment by Morpheus1101** [comment]
Scripts had not been uploaded to the server, this is why there was conflicting information. This has been corrected. Thankyou for the report.
