### ISSUE TITLE
[Client Sided Crash] Yeta Wrench, Basic Capacitor (Shift Right Click>Pickup)

### ISSUE THREAD

**Issue by Ruchian** [MinecraftModDevelopment/New-MMD-Public-Pack#57]
MMD Public Pack - Reloaded, version 1.0.1.1)
Forge Version: 14.23.3.2678
Java Version: 1.8.0_171b11

Short summary: (see title)
Basically picking up a basic capacitor with a yeta wrench using shift right click causes a client sided crash.
Reason: uncertain.

Apparent involved mods when I encountered the problem:
Ender IO 1.12.2 - 5.0.24
Ender Core 1.12.2 - 0.5.22
Thermal Expansion 1.12.2 - 5.4.2.27
Actually Additions 1.12.2 - r134

Long Description:

The setup I have is as followed:

A Basic Capacitor Bank (Ender IO)_, attached to a (basic) Energy Conduit (Ender IO) at the bottom, which receives power from a Energetic Photovoltaic Cell (from Ender IO) and Tier 2 Solar Panels (from the Solar Flux Reborn) is connected on a side to a Simple Alloy Smelter (Ender IO). The Energy Conduit system is further attached to a Simple SAG Mill (Ender IO) and a few Thermal Expansion machines (namely: the Pulveriser (basic), the Compactor (basic) and the Induction Smelter (basic)), as well as the Farmer (from Actually Additions).

I discovered the issue on Multiplayer; on the official public server. I tried recreating the same setup I have in Single Player: World generation is Lost Cities. Biome: Plains. Location, dirt, outside, all in the same chunk, except for the Farmer.

Here's a screenshot from the server:

![enderiocrash](https://user-images.githubusercontent.com/24900404/39779737-666cedc0-530a-11e8-9f52-db92ffcf572f.png)

A screenshot in singleplayer: 

![enderiocrash2](https://user-images.githubusercontent.com/24900404/39780374-5ab9b9de-530c-11e8-95e0-82fec7eb854a.png)

What I try doing here is pick up the Basic Capacitor Bank with the Yeta Wrench. Both of these items are from Ender IO.

What I expect to happen is for the basic capacitor to drop as an item, retaining all of its information (e.g: energy level, side configurations, etc.)

What happens instead is a Client Sided crash. (This happens in both SinglePlayer (Gamemode doesn't matter apparently), and in multiplayer (on the server).

Here's the crash report I'd like to share.

[crash-2018-05-08_21.15.13-client.txt](https://github.com/MinecraftModDevelopment/New-MMD-Public-Pack/files/1985489/crash-2018-05-08_21.15.13-client.txt)

I tested this in a custom profile that contains only EnderIO and Ender Core as its mods. Nothing out of the ordinary happens there though. The block responds normally when Shift Right-Clicked with the Yeta Wrench. I tried making an exceptionally large setup with machines connected to the basic level energy conduit, but it didn't matter. The crash only happens in the MMD Modpack so far I have tested. This is why I decided to write a detailed report here, instead of at https://github.com/SleepyTrousers/EnderIO/issues.

**Comment by Morpheus1101** [comment]
If imj reading the crash report correctly, i believe the offending mod is actually caused by FTBU

**Comment by Morpheus1101** [comment]
Ok, the issue isnt FTBU, but rather EnderIO doing something dumb which they shouldnt be doing and FTBU adding in a crash to specifically catch people doing this.

https://github.com/SleepyTrousers/EnderIO/issues/4618

**Comment by Morpheus1101** [comment]
While this may occur still(unsire) its not an actual bug, but intentional from FTBU catching mods using permissions client side which has been cleared by lex as valid for whats being done in this instance.
