### ISSUE TITLE
[Mod Request] Electroblob's Wizardry

### ISSUE THREAD

**Issue by KamiSami** [MinecraftModDevelopment/New-MMD-Public-Pack#58]
https://minecraft.curseforge.com/projects/electroblobs-wizardry

**Comment by Morpheus1101** [comment]
Sounds interesting an models look good, i dont know myself, im on the fence tbh

**Comment by carstorm** [comment]
Looks interesting. I'm leaning towards approve.

**Comment by ProxyNeko** [comment]
I approve
