### ISSUE TITLE
Grave mod swap

### ISSUE THREAD

**Issue by ProxyNeko** [MinecraftModDevelopment/New-MMD-Public-Pack#6]
As we all agreed the other night (if you remember) we wanted to swap to [Tomb Many Graves 2](https://minecraft.curseforge.com/projects/tomb-many-graves-2) from openblocks I think the current release has in use.

**Comment by TheSpicePhantom** [comment]
what kind of issue?

**Comment by ProxyNeko** [comment]
Not being able to break your own grave in claims and such whereas tomb many graves 2 lets the owner of the grave walk over it or shift as they walk over it (I forget what one) but they get their stuff back even in a claimed area.
But all graves can only be picked up by there owners or broken by creative mode players/staff

**Comment by TheSpicePhantom** [comment]
We'll have a look into it

**Comment by carstorm** [comment]
Since it only adds one block and functions much better, we should implement this IMO!
