### ISSUE TITLE
Mod Request: Translocators 1.8+

### ISSUE THREAD

**Issue by nullifiedcat** [MinecraftModDevelopment/New-MMD-Public-Pack#60]
Description: Utility mod that adds easy short-range item/fluid transfer.

https://minecraft.curseforge.com/projects/translocators-1-8

**Comment by carstorm** [comment]
Seems interesting and useful, specially early-mid game with potential uses even late game still. I approve.

**Comment by Morpheus1101** [comment]
I definitely Approve

**Comment by ProxyNeko** [comment]
Mod added to pack.
