### ISSUE TITLE
Chisel blocks

### ISSUE THREAD

**Issue by nullifiedcat** [MinecraftModDevelopment/New-MMD-Public-Pack#61]
Some of the chisel blocks are hidden from JEI, for example I wanted to craft a Factory block but had to search for recipe elsewhere because JEI refused to show it. That is also true for other Chisel blocks. Would be good of base versions of the blocks were available in JEI

**Comment by ProxyNeko** [comment]
I don't mind this change.
I approve.

**Comment by carstorm** [comment]
Woops, I thumbs it up but never wrote out my response...
I approve.

**Comment by Morpheus1101** [comment]
I believe JEI hiding is on a per client basis

**Comment by carstorm** [comment]
Although true that its client side (I believe) we should have it defaulted as requested.

**Comment by Morpheus1101** [comment]
I'll add it to next update, or some randm time, i dont believe doing this at any stage would affect game play
