### ISSUE TITLE
Mod Request: Exchangers

### ISSUE THREAD

**Issue by nullifiedcat** [MinecraftModDevelopment/New-MMD-Public-Pack#62]
Utility mod adding just a few items: Exchangers that allow quick swapping of placed blocks (works like "Equal Trade" focus from old Thaumcraft)

https://minecraft.curseforge.com/projects/exchangers

**Comment by carstorm** [comment]
This seems like a much more advanced version of the swapping wand from Not Enough Wands. I approve this mod and suggest disabling the swapping wand from NEW.

**Comment by Morpheus1101** [comment]
im good either way on this one, since this is a feature i personally dont use, if it benefits others and a better version then im all for it

**Comment by ProxyNeko** [comment]
I approve the swap

**Comment by ProxyNeko** [comment]
Mod added to pack.
