### ISSUE TITLE
Add in custom values for modded chest plates to Selim backpacks

### ISSUE THREAD

**Issue by carstorm** [MinecraftModDevelopment/New-MMD-Public-Pack#65]
The config file is at "\config\selimpacks.cfg"

**Comment by Morpheus1101** [comment]
![2018-06-03_09 36 57](https://user-images.githubusercontent.com/10524952/40881733-eacb992a-6711-11e8-8566-c42780425bb4.png)
![2018-06-03_09 37 40](https://user-images.githubusercontent.com/10524952/40881734-eaf7df4e-6711-11e8-8dab-fed182cc5117.png)
![2018-06-03_09 38 14](https://user-images.githubusercontent.com/10524952/40881735-eb2a0276-6711-11e8-8a39-f0ac481ee0c8.png)
![2018-06-03_09 38 21](https://user-images.githubusercontent.com/10524952/40881736-eb56892c-6711-11e8-87a7-c1bef2a893b9.png)
