### ISSUE TITLE
[Bug] /dank/null potential dupe

### ISSUE THREAD

**Issue by Virtuoel** [MinecraftModDevelopment/New-MMD-Public-Pack#66]
/dank/nulls can be used to copy NBT from one item to another of the same item, which can be abused to dupe items if you put something like a filled bag in first and then put an empty bag in, which sets both to have the filled bag's NBT.  

The bug has apparently been fixed in dev versions of /dank/null [as of March 15th](https://github.com/p455w0rd/DankNull/issues/95#event-1523235270), but has not yet been released.

**Comment by Morpheus1101** [comment]
I will talk to p455w0rd, he has been ill of late and hasnt been at a computer much to do a lot of work though, but i'll see what i can do.

**Comment by Morpheus1101** [comment]
This has been fixed in Dev

**Comment by Tntdruid** [comment]
Where can you download the dev version?

**Comment by ProxyNeko** [comment]
The fix for this bug is likely out in public versions now (fixed in dev usually implys that the fix is not released yet)

Pack discontinued in favor of a new mod pack with less lag issues. Please see a member of the Public Server Admins team for info on this new pack.
