### ISSUE TITLE
[Mod Request] MmmMmmMmmMmm

### ISSUE THREAD

**Issue by KamiSami** [MinecraftModDevelopment/New-MMD-Public-Pack#67]
https://minecraft.curseforge.com/projects/mmmmmmmmmmmm
Pretty simple and small yet silly mod, you can test how much damage you deal aswell as what is your DPS, you can also give armor to the dummy..

**Comment by carstorm** [comment]
Simple mod that adds one item but can be quite useful (especially at satisfying curiosities w/o killing basemates). I approve.

**Comment by ProxyNeko** [comment]
Such a simple small mod but I feel like something in the pack if not vanilla already shows how much damage a sword/weapon shows how much damage it would do to a player without armour on but that said I am happy if it does end up in the pack.

@Morpheus1101 and @TheSpicePhantom get the final say as I'm of both worlds.

**Comment by TheSpicePhantom** [comment]
I'm totally down for it :D I dont want to kill you anymore Proxy

**Comment by Morpheus1101** [comment]
I added my reaction a while ago :D

**Comment by carstorm** [comment]
ATM 2 yes, 1 no, 1 indifferent. We also had one non-staff member vote it up. Prox can you give a  clear yes or no answer to break the staff tie.

**Comment by Morpheus1101** [comment]
Spice has also all ready added a reaction of approval

**Comment by Morpheus1101** [comment]
Added in v1.0.3

**Comment by carstorm** [comment]
This has not been added in the most recent update like it was supposed to be.

**Comment by ProxyNeko** [comment]
It is currently on the repo so should have been added and if it has not been it will be for 1.0.4
