### ISSUE TITLE
[Mod Request]YABBA

### ISSUE THREAD

**Issue by enderger** [MinecraftModDevelopment/New-MMD-Public-Pack#72]

**Comment by ProxyNeko** [comment]
Closed because 

![No info provided so closed. Reopen when info and link is provided](https://cdn.discordapp.com/attachments/231227095995514880/452092412719005696/Screenshot_20180601-135327_Firefox_Nightly.jpg)

**Comment by enderger** [comment]
I added a description. I misclicked the send button before putting info.

**Comment by Morpheus1101** [comment]
We take curseforge links only

**Comment by enderger** [comment]
The link redirects to curseforge. I just shortened it.

**Comment by enderger** [comment]
Original link: https://minecraft.curseforge.com/projects/yabba?gameCategorySlug=mc-mods&projectID=255177
