### ISSUE TITLE
[Mod Request] Akashic Tome

### ISSUE THREAD

**Issue by Intipablo** [MinecraftModDevelopment/New-MMD-Public-Pack#73]
Akashic Tome: https://minecraft.curseforge.com/projects/akashic-tome

I joined the server and pretty much the whole starting hotbar is just mod guides. This mod is a great solution to that and a simple concept that shouldn't be hard to add to the pack.

**Comment by Morpheus1101** [comment]
Yes i agree that this is indeed an annoying thing i have found.

**Comment by ProxyNeko** [comment]
It might be possible to disable most if not all of the books and just give them to the player in a bag on join but we will see what the others say.

**Comment by carstorm** [comment]
I approve this request.

**Comment by TheSpicePhantom** [comment]
**Look at Proxys Post**

**Comment by TheSpicePhantom** [comment]
It's 2 v 2 as of how i see it here

**Comment by Zaweri** [comment]
I approve of this mod.

**Comment by carstorm** [comment]
Now its 3 v 2 supporting up. IMO " it's 1 more mod that adds just like 1 really useful item" is a plus since it means the mods not bloated doing just one thing (assumedly well) rather than having one feature that you want to use and 50 other things bundled in that you'll never touch.
