### ISSUE TITLE
Robotic Parts config change 

### ISSUE THREAD

**Issue by Skarmarm** [MinecraftModDevelopment/New-MMD-Public-Pack#75]
roboticparts https://minecraft.curseforge.com/projects/roboticparts

**Reason for request**
This request is to change one of these 2 lines to true
![image](https://user-images.githubusercontent.com/30760890/41196682-699fa83c-6c0c-11e8-88d1-dbf3a9286b9d.png)

**Comments** 
The config file is still cyberware

**Comment by Morpheus1101** [comment]
> gamerules {
    S:"Chance of successful drop"=50.0
    B:"Default for gamerule cyberware_dropCyberware"=true
    B:"Default for gamerule cyberware_keepCyberware"=false
}

is now what it looks like
