### ISSUE TITLE
Remove not enough ids and replace it with just enough ids

### ISSUE THREAD

**Issue by Trinsdar** [MinecraftModDevelopment/New-MMD-Public-Pack#76]
**Mod name and link**
\<JustEnoughIDs>
\<https://minecraft.curseforge.com/projects/jeid\>

**Description and reason**
Just enough ids extends the block, item, and biome id limits without the problems that not enough ids has, mainly removing mods and blocks.

**Alternatives**
Not enough ids does, but it's horrible.

**Comments**
apparently you can't remove not enough ids yet, but it's in the works I believe.

**Comment by Trinsdar** [comment]
![just-enough-ids - discord](https://user-images.githubusercontent.com/30245301/42486331-9a1571ac-83c9-11e8-9d11-c91061baef03.png)

**Comment by carstorm** [comment]
I approve this request once version 3 comes out and is tested.

**Comment by ProxyNeko** [comment]
Approved once v3 is out (Might be out by now maybe)

**Comment by ProxyNeko** [comment]
Pack discontinued in favor of a new mod pack with less lag issues. Please see a member of the Public Server Admins team for info on this new pack.
