### ISSUE TITLE
[Mod Request] Morph-Tweaks

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/New-MMD-Public-Pack#8]
Id like to request this mod for the next update..only hard dependancy is codechickenlib which is in the pack all ready: https://minecraft.curseforge.com/projects/morph-tweaks

Main thing thatd be used would be the Enchanting which allows to use ingredients to make what ever enchant and level your wanting without relying on pot luck.

**Comment by carstorm** [comment]
IMO we should add this though the configs will def have to be tweaked some.

**Comment by TheSpicePhantom** [comment]
Yes, coming with the next update

**Comment by ProxyNeko** [comment]
Morph-Tweaks has been added in pack version: 0.0.5
